version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"
    env_file:
      - ./auth-service/.env
    depends_on:
      - postgres

  vehicle-service:
    build: ./vehicle-service
    ports:
      - "8082:8082"
    env_file:
      - ./vehicle-service/.env
    depends_on:
      - postgres

  document-service:
    build: ./document-service
    ports:
      - "8083:8083"
    env_file:
      - ./document-service/.env
    environment:
      - MINIO_ENDPOINT=minio:9000        
      - MINIO_ACCESS_KEY=minio
      - MINIO_SECRET_KEY=minio123
      - USE_SSL=false
    depends_on:
      - postgres
      - minio


  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minio123
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

  user-service:
    build: ./user-service
    ports:
      - "8084:8084"
    env_file:
      - ./user-service/.env
    depends_on:
      - postgres

  mail-service:
    build: ./mail-service
    ports:
      - "8085:8085"
    env_file:
      - ./mail-service/.env


volumes:
  pgdata:
  minio-data:

