version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  auth-service:
    build: ./auth-service
    ports:
      - "8081:8081"
    env_file:
      - ./auth-service/.env
    depends_on:
      - postgres

  vehicle-service:
    build: ./vehicle-service
    ports:
      - "8082:8082"
    env_file:
      - ./vehicle-service/.env
    depends_on:
      - postgres

volumes:
  pgdata:
